_frozen_importlib:222: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
Traceback (most recent call last):
  File "test.py", line 153, in <module>
    factorizer.factorize(report=args.report, max_iteration=max_iterations, fixed_covariance=fixed_covariance, to_report=[50, 100, 200])
  File "/cluster/home/mnguye16/SSVI/SSVI-TF/SSVI/SSVI_TF_interface.py", line 115, in factorize
    self.update_natural_param_batch(dim, col)
  File "/cluster/home/mnguye16/SSVI/SSVI-TF/SSVI/SSVI_TF_interface.py", line 177, in update_natural_param_batch
    di, Di, si = self.estimate_di_Di_si_batch(dim, i, coords, ys, m, S)
  File "/cluster/home/mnguye16/SSVI/SSVI-TF/SSVI/SSVI_TF_robust.py", line 38, in estimate_di_Di_si_batch
    vjs_batch = self.sample_vjs_batch(othercols_concat, otherdims, self.k1)
  File "/cluster/home/mnguye16/SSVI/SSVI-TF/SSVI/SSVI_TF_interface.py", line 415, in sample_vjs_batch
    vj_sample = np.random.multivariate_normal(mi, np.diag(Si), size=k)
  File "mtrand.pyx", line 4521, in mtrand.RandomState.multivariate_normal
  File "/cluster/home/mnguye16/SSVI/SSVI-TF/venv/lib/python3.5/site-packages/scipy/linalg/decomp_svd.py", line 109, in svd
    a1 = _asarray_validated(a, check_finite=check_finite)
  File "/cluster/home/mnguye16/SSVI/SSVI-TF/venv/lib/python3.5/site-packages/scipy/_lib/_util.py", line 238, in _asarray_validated
    a = toarray(a)
  File "/cluster/home/mnguye16/SSVI/SSVI-TF/venv/lib/python3.5/site-packages/numpy/lib/function_base.py", line 461, in asarray_chkfinite
    "array must not contain infs or NaNs")
ValueError: array must not contain infs or NaNs
